typedef enum {
    CHARACTER_MARIO = 0,
    CHARACTER_LUIGI,
    CHARACTER_YOSHI,
    CHARACTER_TOAD,
    CHARACTER_DK,
    CHARACTER_WARIO,
    CHARACTER_PEACH,
    CHARACTER_BOWSER,
    NUM_CHARACTERS
} CharacterID;
